require("tests.unit.config_spec")
require("tests.unit.api_spec")
require("tests.unit.commands_spec")
require("tests.unit.actions_spec")
require("tests.unit.highlights_spec")
require("tests.unit.path_spec")
require("tests.unit.format_spec")
require("tests.unit.fuzzy_spec")
require("tests.unit.search_spec")
require("tests.unit.lualine_spec")
require("tests.unit.scanner_spec")
require("tests.unit.state_spec")
require("tests.unit.expand_spec")
require("tests.unit.window_spec")

require("tests.buffers.open_spec")
require("tests.buffers.locate_spec")
require("tests.buffers.search_spec")
require("tests.buffers.yank_spec")

require("tests.files.open_spec")
require("tests.files.locate_spec")
require("tests.files.search_spec")
require("tests.files.toggle_spec")
require("tests.files.yank_spec")
require("tests.files.create_spec")
require("tests.files.copy_paste_spec")
require("tests.files.cut_paste_spec")
require("tests.files.trash_spec")
require("tests.files.duplicate_spec")
require("tests.files.rename_spec")
require("tests.files.full_tree_spec")
require("tests.files.git_spec")
require("tests.files.last_window_spec")

require("tests.helpers").run()
