describe("nvim-sidebar", function()
  it("loads", function()
    local sidebar = require("nvim-sidebar")

    assert.is_function(sidebar.setup)
    assert.is_function(sidebar.open)
    assert.is_function(sidebar.close)
    assert.is_function(sidebar.toggle)
    assert.is_function(sidebar.focus)
    assert.is_function(sidebar.refresh)
    assert.is_function(sidebar.open_full_tree)
  end)
end)
